# AEGIS - NowBlackout ENSIBS 2025
# Last modified: 2025-04-11
# Models - All Object Class autogenerated from the AEGIS database schema

from typing import Optional
import datetime
import decimal

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, Numeric, String, Table, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    pass


class USERS(Base):
    __tablename__ = 'USERS'

    username: Mapped[str] = mapped_column(String(50), nullable=False)
    first_name: Mapped[str] = mapped_column(String(50), nullable=False)
    last_name: Mapped[str] = mapped_column(String(50), nullable=False)
    can_vote: Mapped[bool] = mapped_column(Boolean, nullable=False)
    user_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    email: Mapped[Optional[str]] = mapped_column(String(50))
    job: Mapped[Optional[str]] = mapped_column(String(50))
    the_role: Mapped[Optional[str]] = mapped_column(String(50))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    BADGES: Mapped[list['BADGES']] = relationship('BADGES', back_populates='USERS_')
    SECRETS: Mapped[list['SECRETS']] = relationship('SECRETS', back_populates='creator_user')
    VOTES: Mapped[list['VOTES']] = relationship('VOTES', back_populates='creator_user')
    ENVELOPES: Mapped[list['ENVELOPES']] = relationship('ENVELOPES', back_populates='USERS_')


t_badges = Table(
    'badges', Base.metadata,
    Column('badge_id', Integer),
    Column('the_user', Integer),
    Column('header_id', String(50), nullable=False),
    Column('issued_at', DateTime, nullable=False),
    Column('expires_at', DateTime, nullable=False),
    Column('json_integrity', String(100), nullable=False),
    Column('json_path', String(100), nullable=False),
    Column('is_revoked', Boolean, nullable=False),
    Column('totp_secret', String(100), nullable=False),
    Column('totp_salt', String(100), nullable=False),
    Column('revoked_at', DateTime),
    Column('revoked_reason', String(50), nullable=False)
)


t_users = Table(
    'users', Base.metadata,
    Column('user_id', Integer),
    Column('username', String(50), nullable=False),
    Column('first_name', String(50), nullable=False),
    Column('last_name', String(50), nullable=False),
    Column('email', String(50)),
    Column('job', String(50)),
    Column('the_role', String(50)),
    Column('can_vote', Boolean, nullable=False),
    Column('created_at', DateTime),
    Column('updated_at', DateTime)
)


class BADGES(Base):
    __tablename__ = 'BADGES'

    header_id: Mapped[str] = mapped_column(String(50), nullable=False)
    issued_at: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    expires_at: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    json_integrity: Mapped[str] = mapped_column(String(100), nullable=False)
    json_path: Mapped[str] = mapped_column(String(100), nullable=False)
    is_revoked: Mapped[bool] = mapped_column(Boolean, nullable=False)
    totp_secret: Mapped[str] = mapped_column(String(100), nullable=False)
    totp_salt: Mapped[str] = mapped_column(String(100), nullable=False)
    revoked_reason: Mapped[str] = mapped_column(String(50))
    badge_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    the_user: Mapped[Optional[int]] = mapped_column(ForeignKey('USERS.user_id'))
    revoked_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    USERS_: Mapped[Optional['USERS']] = relationship('USERS', back_populates='BADGES')
    SHARES: Mapped[list['SHARES']] = relationship('SHARES', back_populates='BADGES_')


class SECRETS(Base):
    __tablename__ = 'SECRETS'

    secret_value: Mapped[str] = mapped_column(String(500), nullable=False)
    secret_type: Mapped[str] = mapped_column(String(50), nullable=False)
    secret_share_n: Mapped[int] = mapped_column(Integer, nullable=False)
    secret_share_k: Mapped[int] = mapped_column(Integer, nullable=False)
    used: Mapped[bool] = mapped_column(Boolean, nullable=False)
    secret_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    secret_action: Mapped[Optional[str]] = mapped_column(String(50))
    creator_user_id: Mapped[Optional[int]] = mapped_column(ForeignKey('USERS.user_id'))
    issued_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    used_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    creator_user: Mapped[Optional['USERS']] = relationship('USERS', back_populates='SECRETS')
    SHARES: Mapped[list['SHARES']] = relationship('SHARES', back_populates='SECRETS_')


class VOTES(Base):
    __tablename__ = 'VOTES'

    question: Mapped[str] = mapped_column(String(300), nullable=False)
    vote_type: Mapped[str] = mapped_column(String(500), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False)
    vote_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    creator_user_id: Mapped[Optional[decimal.Decimal]] = mapped_column(ForeignKey('USERS.user_id'))
    k_required: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    vote_status: Mapped[Optional[str]] = mapped_column(String(50))
    opened_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    timeout_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    closed_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    creator_user: Mapped[Optional['USERS']] = relationship('USERS', back_populates='VOTES')
    ENVELOPES: Mapped[list['ENVELOPES']] = relationship('ENVELOPES', back_populates='VOTES_')


class ENVELOPES(Base):
    __tablename__ = 'ENVELOPES'

    the_date: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    vote_choice: Mapped[decimal.Decimal] = mapped_column(Numeric, nullable=False)
    user_signature_valid: Mapped[bool] = mapped_column(Boolean, nullable=False)
    entry_hash: Mapped[str] = mapped_column(String(100), nullable=False)
    current_hash: Mapped[str] = mapped_column(String(100), nullable=False)
    siem_loged: Mapped[bool] = mapped_column(Boolean, nullable=False)
    envelope_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    the_vote: Mapped[Optional[int]] = mapped_column(ForeignKey('VOTES.vote_id'))
    the_user: Mapped[Optional[int]] = mapped_column(ForeignKey('USERS.user_id'))
    the_badge: Mapped[Optional[int]] = mapped_column(ForeignKey('badges.badge_id'))
    prev_hash: Mapped[Optional[str]] = mapped_column(String(100))

    USERS_: Mapped[Optional['USERS']] = relationship('USERS', back_populates='ENVELOPES')
    VOTES_: Mapped[Optional['VOTES']] = relationship('VOTES', back_populates='ENVELOPES')
    NONCES: Mapped[list['NONCES']] = relationship('NONCES', back_populates='ENVELOPES_')


class SHARES(Base):
    __tablename__ = 'SHARES'

    share_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    the_secret: Mapped[Optional[int]] = mapped_column(ForeignKey('SECRETS.secret_id'))
    the_badge: Mapped[Optional[int]] = mapped_column(ForeignKey('BADGES.badge_id'))
    shamir_value: Mapped[Optional[str]] = mapped_column(String(50))
    used_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    BADGES_: Mapped[Optional['BADGES']] = relationship('BADGES', back_populates='SHARES')
    SECRETS_: Mapped[Optional['SECRETS']] = relationship('SECRETS', back_populates='SHARES')


class NONCES(Base):
    __tablename__ = 'NONCES'

    used: Mapped[bool] = mapped_column(Boolean, nullable=False)
    nonce_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True)
    nonce: Mapped[Optional[str]] = mapped_column(String(50))
    the_envelope: Mapped[Optional[int]] = mapped_column(ForeignKey('ENVELOPES.envelope_id'))
    issued_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    used_by: Mapped[Optional[decimal.Decimal]] = mapped_column(ForeignKey('users.user_id'))
    used_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    ENVELOPES_: Mapped[Optional['ENVELOPES']] = relationship('ENVELOPES', back_populates='NONCES')
